name: 🚀 CK Crypto News Bot - Auto Every 3 Hours

on:
  schedule:
    - cron: "5 0 * * *"    # 07:05 VN
    - cron: "5 3 * * *"    # 10:05 VN
    - cron: "5 6 * * *"    # 13:05 VN
    - cron: "5 9 * * *"    # 16:05 VN
    - cron: "5 12 * * *"   # 19:05 VN
    - cron: "5 15 * * *"   # 22:05 VN
    - cron: "5 18 * * *"   # 01:05 VN
    - cron: "5 21 * * *"   # 04:05 VN
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure sent_ids file exists
        run: |
          today=$(TZ='Asia/Ho_Chi_Minh' date +%Y%m%d)
          if [ ! -f sent_ids_${today}.json ]; then echo "[]" > sent_ids_${today}.json; fi

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python main.py
